version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    ignore:
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: better-sqlite3
        update-types: ["version-update:semver-major"]
  - package-ecosystem: pip
    directory: /pyserver
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
